# Extends the mainnet preset
PRESET_BASE: 'mainnet'
# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 400
# Thu Jun 16 2022 16:00:00 GMT+0000
MIN_GENESIS_TIME: 1655395200
# Gensis fork
GENESIS_FORK_VERSION: 0x60000069
# Network starts at MIN_GENESIS_TIME + GENESIS_DELAY
GENESIS_DELAY: 1800


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x61000070
ALTAIR_FORK_EPOCH: 3
# BELLATRIX
BELLATRIX_FORK_VERSION: 0x62000071
BELLATRIX_FORK_EPOCH: 6
TERMINAL_TOTAL_DIFFICULTY: 12000000000 
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Sharding
SHARDING_FORK_VERSION: 0x03000000
SHARDING_FORK_EPOCH: 18446744073709551615


# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 6
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 2
# 2**8 (= 256) epochs ~27 hoursaw
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 16 blocks is ~190s
ETH1_FOLLOW_DISTANCE: 16


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536
# 220,000,000,000 Gwei
MAX_EFFECTIVE_BALANCE: 220000000000


# Deposit contract
# ---------------------------------------------------------------
# Custom Ethereum testnet
DEPOSIT_CHAIN_ID: 2828
DEPOSIT_NETWORK_ID: 2828
DEPOSIT_CONTRACT_ADDRESS: 0x000000000000000000000000000000000000cafe