chain = "mainnet"
networkid = 7420

externalcl = true

miner.gaslimit = 42000000
GasPrice = 1000000000 # 1 Gwei

datadir = "./devnet-data/execution"
"authrpc.jwtsecret" = "./configs/shared/secrets/jwt.hex"
nat = "any"
ws = false
http = true
"http.addr" = "localhost"
"http.api" = "erigon" # "eth,erigon,engine,debug,trace"
"http.vhosts" = "*"
"authrpc.addr" = "localhost"
"authrpc.port" = 8551
"authrpc.vhosts" = "*"

# ethstats = "${NODE_NAME}@${ETH_STATS_IP}"

bootnodes = []
