# The full config options can be found here:
# https://geth.ethereum.org/docs/fundamentals/config-files

[Eth]
NetworkId = 3030

[Eth.Miner]
GasCeil = 42000000
GasPrice = 1000000000 # 1 Gwei

[Node]
DataDir = "./devnet-data/execution"
IPCPath = "./devnet-data/execution/geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"] # ["net", "eth", "web3", "debug", "engine", "txpool"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "eth"]  # ["net", "eth", "web3", "debug", "engine", "txpool"]
# GraphQLVirtualHosts = ["localhost"]

# Engine API
JWTSecret = "./configs/shared/secrets/jwt.hex"
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"] # ["*"]

[Node.P2P]
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []

MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Ethstats]
# URL = "node_name@server_address"
