testnet-dir = "./configs/devnet/shared"
datadir = "./devnet-data/consensus"
execution-jwt = "./configs/shared/secrets/jwt.hex"
execution-endpoint = "http://localhost:8551"
subscribe-all-subnets = true
listen-address = "localhost"
eth1 = true
http = true
http-port = 4000
enr-udp-port = 9000
enr-tcp-port = 9000
discovery-port = 9000
enable-private-discovery = true
enr-address = "0.0.0.0"
metrics = true
metrics-port = 5054