testnet-dir = "./configs/testnet/shared"
datadir = "./testnet-data/consensus"
execution-jwt = "./configs/shared/secrets/jwt.hex"
execution-endpoint = "http://localhost:8551"
subscribe-all-subnets = true
listen-address = "0.0.0.0"
eth1 = true
http = true
http-port = 4000
enr-udp-port = 9000
enr-tcp-port = 9000
discovery-port = 9000
enable-private-discovery = true
enr-address = "0.0.0.0"
metrics = true
metrics-port = 5054
boot-nodes = 'enr:-MK4QPAebhGrV0IdXCaVQ33cL-5oySUvBXPkXZTHhCDrqMOtITlhab5B6PL9hfQY5NuRF5ctLcSFhHMCdLT4RWxxo-SGAYiVi7DIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCvClM1QgEABP__________gmlkgnY0gmlwhCKNxNSJc2VjcDI1NmsxoQISdsDnr_lxpAXRQmeOu-F_eAtxypZI4ctFavqdagbka4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A,enr:-MK4QMEZyb5vA6A4664OJNbdRF7QQHtSMISOqU9CF8qcdB7BBjX0HsQY92roqS-0n1wTyiuCFT0weAIE7FkukdnjL0GGAYli9q2wh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCvClM1QgEABP__________gmlkgnY0gmlwhCJbnOCJc2VjcDI1NmsxoQJvUBwASZv0klLo0Zz51eb_LCQx-lNrNPp-lLULQBTpfYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A'