'data-path' = './testnet-data/execution'
'genesis-file' = './configs/testnet/shared/genesis.json'
'network-id' = 4201
'engine-jwt-secret' = './configs/shared/secrets/jwt.hex'
'rpc-http-enabled' = true
'rpc-http-port' = 8545
'bootnodes' = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.141.196.212:30303","enode://4cee52dc3cdc0f9466d40354c0ae038b561eff0409f01092d44d692f35797a0f3e796481c5ad1ca9afb4ea00dcceaaddbf3a79ec311221bfad3567ba347e329b@34.91.156.224:30303"]
