"chain" = "mainnet"
"networkid" = 42

"miner.gaslimit" = 42000000

"datadir" = "./mainnet-data/execution"
"authrpc.jwtsecret" = "./configs/shared/secrets/jwt.hex"
"nat" = "any"
"ws" = false
"http" = true
"http.addr" = "localhost"
"http.api" = "erigon,engine" # "eth,erigon,engine,debug,trace"
"http.vhosts" = "*"
"authrpc.addr" = "localhost"
"authrpc.port" = 8551
"authrpc.vhosts" = "*"
"snapshots" = false
"prune" = "htc"
"private.api.addr" = "localhost:9091"

# Bootnodes
"bootnodes" = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.73.193:30303", "enode://276f14e4049840a0f5aa5e568b772ab6639251149a52ba244647277175b83f47b135f3b3d8d846cf81a8e681684e37e9fc10ec205a9841d3ae219aa08aa9717b@34.32.192.211:30303"]

# "ethstats" = "<NODE_NAME>:<ETH_STATS_SECRET>@stats.execution.mainnet.lukso.network"

