# LUKSO config

# Extends the mainnet preset
PRESET_BASE: 'mainnet'

# Free-form short name of the network that this configuration applies to
# Must match the regex: [a-z0-9\-]
CONFIG_NAME: 'lukso-devnet'

# Genesis
# ---------------------------------------------------------------
# Min Genesis Validators in Genesis state
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 3096
# Min Genesis Time: Monday, 15 May 2023 14:20:00 (GMT)
MIN_GENESIS_TIME: 1684160400
# 2400 seconds (40 Min)
GENESIS_DELAY: 2400
# Final Network start time: 1684160400 + 2400 = 1684162800
# Monday, 15 May 2023 15:00:00 (GMT)

# Transition
# ---------------------------------------------------------------
# Configs are present in case a need arose to manually select a particular proof of work fork to follow in case of trouble
# The total (cumulative) difficulty threshold required of the final block mined in Ethereum
TERMINAL_TOTAL_DIFFICULTY: 0
# Designates the hash of the terminal PoW block if set
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# Specifies the terminal block hash epoch to manual
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 1

# Deposit contract and execution chain IDs
# ---------------------------------------------------------------
# Custom Ethereum devnet
DEPOSIT_CHAIN_ID: 7420
DEPOSIT_NETWORK_ID: 7420
DEPOSIT_CONTRACT_ADDRESS: 0xcafe00000000000000000000000000000000cafe

# Forks
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Gensis fork
GENESIS_FORK_VERSION: 0x74200001

# Altair
ALTAIR_FORK_VERSION: 0x74200002
ALTAIR_FORK_EPOCH: 0

# Belatrix
BELLATRIX_FORK_VERSION: 0x74200003
BELLATRIX_FORK_EPOCH: 0

# Capella
# Epoch to timestamp: 32 * 12 * 7042 - 2 + MIN_GENESIS_TIME + GENESIS_DELAY
CAPELLA_FORK_VERSION: 0x74200004
CAPELLA_FORK_EPOCH: 42

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 2**5 (= 32) slots 6.4 minutes
SLOTS_PER_EPOCH: 32
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 12
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 2048

# Sync committee
# ---------------------------------------------------------------
# 2**9 (= 512)
SYNC_COMMITTEE_SIZE: 512
# 2**8 (= 256)
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Validator Stakes
# ---------------------------------------------------------------
# 2**5 * 10**9 (= 32,000,000,000) Gwei
MAX_EFFECTIVE_BALANCE: 32000000000
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
